#pragma config(Sensor, in1,    potLeft,        sensorPotentiometer)
#pragma config(Sensor, in2,    potRight,       sensorPotentiometer)
#pragma config(Sensor, in3,    gyro,           sensorGyro)
#pragma config(Sensor, in4,    acX,            sensorAccelerometer)
#pragma config(Sensor, in5,    acY,            sensorAccelerometer)
#pragma config(Motor,  port2,           lFront,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           rBack,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           leftLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftLiftY,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightLiftY,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rFront,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           lBack,         tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{



}
