#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
#pragma config(Sensor, in2,    pPowerExp,      sensorAnalog)
#pragma config(Sensor, in3,    gyro,           sensorGyro)
#pragma config(Sensor, in4,    acX,            sensorAnalog)
#pragma config(Sensor, in5,    acY,            sensorAnalog)
#pragma config(Sensor, in6,    acZ,            sensorAnalog)
#pragma config(Sensor, dgtl12, initIndicator,  sensorLEDtoVCC)
#pragma config(Motor,  port2,           lBack,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           lFront,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           clawY,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rLiftT,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           botLift,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           lLiftT,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rBack,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rFront,        tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{



}
