#pragma config(UserModel, "C:/Users/rstudent/code/39z-starstruck/39zconfig.c")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)



float curHeading = 0; //Current X Velociy, Y Velocity, X Position, Y Position, Heading
float interval = 0.075; //Interval is in SECONDS


//Calculates Initial Position and Heading based on current side and team
void initPos()
{
	SensorType[gyro] = sensorNone;
	wait1Msec(1000);
	SensorType[gyro] = sensorGyro;
	wait1Msec(2000);
	SensorValue(gyro) = 0;
}

//Tracks Current Location, Velocity, and Heading while the track task is being run
task track()
{
	while (true)
	{
		curHeading = SensorValue(gyro)/10.;
		delay (interval*1000);
	}
}


void pre_auton()
{
	initPos();
	clearDebugStream();
}

task main()
{
	pre_auton();
	//startTask(track);
	while(true)
	{
		writeDebugStreamLine("CurHeading: %f", curHeading);
		delay(500);

	}
}
